In [2]:
import torch
import torch.nn as nn

m = nn.Sigmoid()
loss = nn.BCELoss()
input = torch.randn(3, requires_grad=True)
target = torch.empty(3).random_(2)


In [3]:
print(input)

tensor([ 1.6855,  0.7115, -0.7296])


In [4]:
print(target)

tensor([ 0.,  1.,  1.])


In [7]:
output = loss(m(input), target)
output.backward()

In [8]:
output

tensor(1.1260)

In [1]:
dict = {1:0, 2:1}

In [2]:
dict[2]

1

In [3]:
import pandas as pd

mapping_txt = pd.read_csv('/Users/wanglei/Downloads/Charades/Charades_v1_mapping.txt', delim_whitespace=True, header = None)

In [4]:
mapping_txt

0     1     2
0    c000  o009  v008
1    c001  o009  v016
2    c002  o009  v023
3    c003  o009  v025
4    c004  o009  v026
5    c005  o009  v030
6    c006  o012  v001
7    c007  o012  v006
8    c008  o012  v012
9    c009  o033  v016
10   c010  o033  v018
11   c011  o033  v018
12   c012  o033  v026
13   c013  o033  v030
14   c014  o033  v032
15   c015  o025  v008
16   c016  o025  v014
17   c017  o025  v016
18   c018  o025  v023
19   c019  o025  v024
20   c020  o001  v008
21   c021  o001  v012
22   c022  o001  v016
23   c023  o001  v023
24   c024  o001  v025
25   c025  o004  v001
26   c026  o004  v008
27   c027  o004  v012
28   c028  o004  v016
29   c029  o004  v019
..    ...   ...   ...
127  c127  o015  v026
128  c128  o022  v008
129  c129  o022  v005
130  c130  o017  v016
131  c131  o034  v009
132  c132  o034  v031
133  c133  o002  v000
134  c134  o002  v010
135  c135  o002  v018
136  c136  o036  v006
137  c137  o036  v008
138  c138  o036  v023
139  c139  o019  v030
140  c140  o013  v006
141  c141  o013  v007
142  c142  o028  v001
143  c143  o028  v012
144  c144  o018  v006
145  c145  o024  v032
146  c146  o000  v000
147  c147  o016  v002
148  c148  o009  v003
149  c149  o000  v009
150  c150  o000  v017
151  c151  o000  v018
152  c152  o000  v019
153  c153  o000  v020
154  c154  o000  v022
155  c155  o009  v028
156  c156  o016  v005

[157 rows x 3 columns]

In [5]:
c_label = []
v_label = []

for i in range(mapping_txt.shape[0]):
    # print(i)
    class_l = int(mapping_txt.iloc[i, 0][1:4])
    class_v = int(mapping_txt.iloc[i, 2][1:4])
    c_label.append(class_l)
    v_label.append(class_v)

In [6]:
new_dict = {k: v for k, v in zip(c_label, v_label)}

In [7]:
new_dict[11]

18

In [15]:
import numpy as np
import torch
x = torch.from_numpy(np.array([0, 1, 2, 3, 4]))
x

tensor([ 0,  1,  2,  3,  4])

In [13]:
x[0]

tensor(0)

In [12]:
new_dict[x[0]]

KeyError: tensor(0)